language: r
cache: packages
    
warnings_are_errors: false

services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rapbase; USE rapbase; CREATE TABLE testTable (id INT, someText VARCHAR(50), someInt INT, someFloat DOUBLE, someTime DATETIME);'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

r_github_packages: 
  - jimhester/covr

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: rel

after_success:
  - travis_wait Rscript -e 'covr::codecov()'
  
