language: r
cache: packages
    
r:
  - oldrel
  - release
  - devel

env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE
    
warnings_are_errors: false

services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rapbase; USE rapbase; CREATE TABLE testTable (id INT, someText VARCHAR(50), someInt INT, someFloat DOUBLE, someTime DATETIME);'

r_github_packages: 
  - jimhester/covr
  - jimhester/lintr
  - r-lib/pkgdown

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - |
    if [[ "$TRAVIS_R_VERSION_STRING" == "release" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'covr::codecov()'
    fi
  - rm -rf rapbase.Rcheck
  - Rscript -e 'pkgdown::build_site()'
  
deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_PAT
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
