services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dev/db/mysql:/docker-entrypoint-initdb.d

  dev:
    depends_on:
      - db
    image: rapporteket/rstudio:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - ../.:/home/rstudio/repos
    ports:
      - "8787:8787"
    environment:
      DISABLE_AUTH: "true"
      MYSQL_DB_LOG: db_log
      MYSQL_DB_AUTOREPORT: db_autoreport

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8888:8080
