services:
  db:
    image: mysql:8
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root

  dev:
    depends_on:
      - db
    image: rapporteket/dev:weekly
    volumes:
      - .:/home/rstudio/rapbase/
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      DISABLE_AUTH: "true"
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
