# dummy config entry
nordummy:
  host : dummy_db_hostname.no
  name : dummy_db_name
  user : dummy_db_username
  pass : dummy_db_password
  disp : dummy_display_name

# for testing, on localhost travis
rapbase:
  host : 127.0.0.1
  name : rapbase
  user : root
  pass : root
  disp : ForTestingOnly

# for logging tests with database as target
raplog:
  host : db
  name : raplog
  user : root
  pass : root
  disp : ForLogDevOnly

# for auto report tests with database as target
autoreport:
  host : db
  name : autoreport
  user : root
  pass : root
  disp : ForAutoReportDevOnly

# for staging data tests with database as target
staging:
  host : db
  name : staging
  user : root
  pass : root
  disp : ForStagingDataDevOnly

# for testing, in dev container
dev:
  host : db
  name : rapbase
  user : root
  pass : root
  disp : ForDevOnly
