on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      GITHUB_ACTIONS_RUN_DB_UNIT_TESTS: true
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Db unit tests in ubuntu/linux only
        if: runner.os != 'Windows'
        run: |
          if [[ ${{ runner.os }} == Linux ]]; then
            echo "GITHUB_ACTIONS_RUN_DB_UNIT_TESTS=true" >> $GITHUB_ENV
            echo "DB_HOST=localhost" >> $GITHUB_ENV
            echo "DB_USER=root" >> $GITHUB_ENV
            echo "DB_PASS=root" >> $GITHUB_ENV
          else
            echo "GITHUB_ACTIONS_RUN_DB_UNIT_TESTS=false" >> $GITHUB_ENV
          fi

      - name: Set up MySQL, ubuntu only
        if: runner.os == 'Linux'
        run: |
          sudo /etc/init.d/mysql start

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}