on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      GITHUB_ACTIONS_RUN_DB_UNIT_TESTS: true
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: root
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
  
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}