on:
  issues:
    types:
      - opened
      - reopened
      - transferred

name: Add issue to project

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Rapporteket/projects/7
          github-token: ${{ secrets.PROJECT_TOKEN }}
